modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Passive%20Shield"
logoFile="icon.png"

[[mods]]
modId="passiveshield"
version="3.2"
displayName="Passive Shield"
displayURL="https://curseforge.com/minecraft/mc-mods/passive-shield"
authors="Rick South"
description='''The shield is hidden in the offhand until used, and they can passively block damage when held.
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.passiveshield]]
    modId="collective"
    mandatory=true
    versionRange="[6.45,)"
    ordering="NONE"
    side="BOTH"