modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Passive%20Shield"
logoFile="icon.png"

[[mods]]
modId="passiveshield"
version="3.6"
displayName="Passive Shield"
displayURL="https://serilum.com/mod/passive-shield"
authors="Rick South"
description='''The shield is hidden in the offhand until used, and they can passively block damage when held.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, Michael W. S., Nahuel Fernandez, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.passiveshield]]
    modId="collective"
    mandatory=true
    versionRange="[7.80,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.passiveshield]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.21.1]"
    ordering="NONE"
    side="BOTH"
