modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Passive%20Shield"
logoFile="icon.png"

[[mods]]
modId="passiveshield"
version="3.4"
displayName="Passive Shield"
displayURL="https://serilum.com/mod/passive-shield"
authors="Rick South"
description='''The shield is hidden in the offhand until used, and they can passively block damage when held.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, BirdieMiner, Cherriesaurus, Jack, Jeremy Langford, Michael W. S., pepe1191, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.passiveshield]]
    modId="collective"
    type="required"
    versionRange="[7.54,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.passiveshield]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "passiveshield.mixins.json"